<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>NdiMerger.Sources</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DirectShowLib.Standard" Version="2.1.0" />
    <PackageReference Include="NDILibDotNet6" Version="1.0.11" />
    <PackageReference Include="Spout2.NET" Version="0.1.0-alpha.2" />
    <PackageReference Include="Vortice.Direct3D11" Version="3.8.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NdiMerger.Core\NdiMerger.Core.csproj" />
  </ItemGroup>

</Project>
